[space]
xmin = 0.0
xmax = 2.0
ymin = 0.0
ymax = 1.0
hx = 0.01
hy = 0.01

[time]
t0 = 0.0
tfinal = 15.0
dt = 0.001
scheme = "ExplicitEuler"

[physics]
rho = 1.0
nu = 0.001    # Fluide type eau (Re ~ 120)

[obstacle]
cx = 0.5
cy = 0.51     # Légèrement décalé pour l'instabilité
radius = 0.06

[boundary]
left = "Dirichlet"
left_val = 1.0
inlet_profile = "Constant"
right = "Neumann"
bottom = "Neumann"
top = "Neumann"

[output]
results = "results/Karman"
name = "Karman_Re120_Explicit_Euler"